# Site settings
title: 김광호의 포트폴리오
description: 'Business Card Page'
url: 'https://github.com/rodvkf72'
baseurl: ''
profilepic: '/images/khki.png'
bkimage: '/images/bk2.png'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Kwang Ho Kim'
  email: rodvkf72@naver.com
  #twitter_username: rodvkf72
  username: rodvkf72
  facebook_username: rodvkf72
  github_username:  rodvkf72
  linkedin_username:  thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
